POST  http://127.0.0.1:8080/users/signup
Content-Type: application/json

{
    "name":"abdulrhman",
    "email":"abdulrhman@gmail.com",
    "password" : "12345678",
    "role" : "admin"
}
###
PUT  http://127.0.0.1:8080/users/1
Content-Type: application/json

{
    "name":"abdulrhman",
    "email":"abdulrhmanemail.com",
    "password" : "12345678",
    "role" : "admin"
}